### ISSUE TITLE
SDL Symbol not found

### ISSUE THREAD

**Issue by brianbruggeman** [HexDecimal/libtcod-cffi#16]
So after a pip install and a find/replace from libtcodpy to tcod, I ended up with this problem:

```
Traceback (most recent call last):
  File "<redacted>/bin/<readacted>", line 11, in <module>
    load_entry_point('<readacted>', 'console_scripts', '<readacted>')()
  File "<redacted>/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "<redacted>/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "<redacted>/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "<redacted>/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<redacted>/__init__.py", line 40, in <module>
    from .utils import get_logger, main_menu  # noqa
  File "<redacted>/utils/__init__.py", line 3, in <module>
    from .ui import *  # noqa
  File "<redacted>/utils/ui/__init__.py", line 2, in <module>
    from .keys import *  # noqa
  File "<redacted>/utils/ui/keys.py", line 2, in <module>
    import tcod as tcod
  File "<redacted>/lib/python3.6/site-packages/tcod/__init__.py", line 20, in <module>
    from tcod.libtcodpy import *
  File "<redacted>/lib/python3.6/site-packages/tcod/libtcodpy.py", line 10, in <module>
    from tcod.libtcod import *
  File "<redacted>/lib/python3.6/site-packages/tcod/libtcod.py", line 85, in <module>
    from tcod._libtcod import lib, ffi
ImportError: dlopen(<redacted>/lib/python3.6/site-packages/tcod/_libtcod.abi3.so, 2): Symbol not found: _SDL_CaptureMouse
  Referenced from: <redacted>/lib/python3.6/site-packages/tcod/_libtcod.abi3.so
  Expected in: /Library/Frameworks/SDL2.framework/Versions/A/SDL2
 in <redacted>/lib/python3.6/site-packages/tcod/_libtcod.abi3.so
```

As a note I can install just fine from the most recent bitbucket pull of libtcod using scons.  And if I point my virtual environment to the `<libtcod-repo-path>/python` folder, I can do a quick `pip install -e .` without an issue.

It feels like SDL is not getting picked up properly.  Any thoughts?

Note I'm on a mac.

**Comment by brianbruggeman** [comment]
I upgraded to a new SDL2 version, and now libtcod-ffi is flawless.  Sorry for the read.
