### ISSUE TITLE
Trouble using pip install with Python3.3

### ISSUE THREAD

**Issue by jdklassen** [HexDecimal/libtcod-cffi#2]
Trying to upgrade tdl in Python 3.3.2 on linux64 (Fedora 20). Running `pip install libtcod-cffi` does not work. I tried several things, see https://github.com/jdklassen/libtcod-cffi/commit/e66c5d0c0481b4ebaf0f894dfe23d0062ccb344c for the changes I made to get as far as I eventually did.
First error I got was this:

```
Running setup.py install for libtcod-cffi
    Complete output from command /home/jdklassen/projects/env/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-e40lon-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-i4zb04-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jdklassen/projects/env/include/site/python3.3/libtcod-cffi:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.3
    creating build/lib.linux-x86_64-3.3/tcod
    copying tcod/__init__.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/parser.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/sys_.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/dijkstra.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/libtcod.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/console.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/color.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/image.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/bsp.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/path.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/map.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/heightmap.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/random.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/namegen.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/noise.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/line.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/mouse.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/version.txt -> build/lib.linux-x86_64-3.3/tcod
    creating build/lib.linux-x86_64-3.3/tcod/lib
    copying tcod/lib/LIBTCOD-LICENSE.txt -> build/lib.linux-x86_64-3.3/tcod/lib
    copying tcod/lib/LIBTCOD-CREDITS.txt -> build/lib.linux-x86_64-3.3/tcod/lib
    copying tcod/lib/README-SDL.txt -> build/lib.linux-x86_64-3.3/tcod/lib
    creating build/lib.linux-x86_64-3.3/tcod/lib/linux64
    copying tcod/lib/linux64/libtcod.so -> build/lib.linux-x86_64-3.3/tcod/lib/linux64
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c'
    creating build/temp.linux-x86_64-3.3
    building 'tcod._libtcod_cp33_x64' extension
    creating build/temp.linux-x86_64-3.3/build
    creating build/temp.linux-x86_64-3.3/build/temp.linux-x86_64-3.3
    gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Itcod/include/libtcod-1.5 -IRelease/tcod/ -I/usr/include/python3.3m -c build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c -o build/temp.linux-x86_64-3.3/build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.o /O2 /W3
    gcc: error: /O2: No such file or directory
    gcc: error: /W3: No such file or directory
    error: command 'gcc' failed with exit status 1
```

Looked for '/O2' and '/W3', found them in build_libtcod.py in extra_compile_args. From what I could find (e. g. http://stackoverflow.com/questions/22526570/what-are-equivalent-gcc-flags-for-visual-studio-warning-levels), these appear to be from visual studio. I imagine they should have some sort of check for compiler before adding them, but to see how far I could get, I removed them completely. (From now on, I used `python setup.py sdist` to build the libtcod-cffi-0.2.1.tar.gz and `pip install ../path/to/file`. Couldn't use PyPI to get my custom changes... Hopefully this was the right way to build it and I didn't break anything else.) Then I started to get this error:

```
  Running setup.py install for libtcod-cffi
    Complete output from command /home/jdklassen/projects/env/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-f02m9x-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zd84z8-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jdklassen/projects/env/include/site/python3.3/libtcod-cffi:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.3
    creating build/lib.linux-x86_64-3.3/tcod
    copying tcod/__init__.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/parser.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/sys_.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/dijkstra.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/libtcod.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/console.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/color.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/image.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/bsp.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/path.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/map.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/heightmap.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/random.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/namegen.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/noise.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/line.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/mouse.py -> build/lib.linux-x86_64-3.3/tcod
    copying tcod/version.txt -> build/lib.linux-x86_64-3.3/tcod
    creating build/lib.linux-x86_64-3.3/tcod/lib
    copying tcod/lib/LIBTCOD-LICENSE.txt -> build/lib.linux-x86_64-3.3/tcod/lib
    copying tcod/lib/LIBTCOD-CREDITS.txt -> build/lib.linux-x86_64-3.3/tcod/lib
    copying tcod/lib/README-SDL.txt -> build/lib.linux-x86_64-3.3/tcod/lib
    creating build/lib.linux-x86_64-3.3/tcod/lib/linux64
    copying tcod/lib/linux64/libtcod.so -> build/lib.linux-x86_64-3.3/tcod/lib/linux64
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c'
    creating build/temp.linux-x86_64-3.3
    building 'tcod._libtcod_cp33_x64' extension
    creating build/temp.linux-x86_64-3.3/build
    creating build/temp.linux-x86_64-3.3/build/temp.linux-x86_64-3.3
    gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Itcod/include/libtcod-1.5 -IRelease/tcod/ -I/usr/include/python3.3m -c build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c -o build/temp.linux-x86_64-3.3/build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.o
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c: In function ‘TDL_list_get_bool’:
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c:400:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         return (bool)TCOD_list_get(l, idx);
                ^
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c: In function ‘TDL_list_get_char’:
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c:404:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         return (char)TCOD_list_get(l, idx);
                ^
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c: In function ‘TDL_list_get_int’:
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c:408:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         return (int)TCOD_list_get(l, idx);
                ^
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c: In function ‘TDL_list_get_float’:
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c:413:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return *(float*)&val;
         ^
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c: In function ‘TDL_list_get_dice’:
    build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.c:427:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return *(TCOD_dice_t*)&val;
         ^
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-3.3/build/temp.linux-x86_64-3.3/tcod._libtcod_cp33_x64.o -Ltcod/lib/linux64/ -L/usr/lib64 -llibtcod -lpython3.3m -o build/lib.linux-x86_64-3.3/tcod/_libtcod_cp33_x64.cpython-33m.so
    /usr/bin/ld: cannot find -llibtcod
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
```

Following suggested advice from http://stackoverflow.com/a/21647591, I ran `ld -L tcod/lib/linux64/ -llibtcod --verbose` (options copied from the pip log) and I can see from the output that it is searching for 'tcod/lib/linux64//liblibtcod.so' (and not, I assume 'tcod/lib/linux64/libtcod.so'). I looked in build_libtcod.py again and found _get_library_dirs_crossplatform() and _get_libraries_crossplatform() and modified their linux cases to remove the '/' and the 'lib'.

Now it pip installs nicely, but now (and after pip install tdl), I get this error:

```
>>> import tdl
Traceback (most recent call last):
  File "/home/jdklassen/projects/env/lib/python3.3/site-packages/tcod/libtcod.py", line 30, in <module>
    import _libtcod # PyPy
ImportError: No module named '_libtcod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdklassen/projects/env/lib/python3.3/site-packages/tdl/__init__.py", line 73, in <module>
    from tcod import ffi as _ffi
  File "/home/jdklassen/projects/env/lib/python3.3/site-packages/tcod/__init__.py", line 20, in <module>
    from .libtcod import lib, ffi, _lib, _ffi
  File "/home/jdklassen/projects/env/lib/python3.3/site-packages/tcod/libtcod.py", line 40, in <module>
    _libtcod = _importlib.import_module(_module_name, 'tcod')
  File "/home/jdklassen/projects/env/lib64/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtcod.so: cannot open shared object file: No such file or directory
>>>
```

This is now well beyond what I know. Inspecting further I found two things that might be useful:
1. the variable _module_name in the second last traceback is '._libtcod_cp33_x64'
2. libtcod.py does append a reasonable looking path to os.environ['PATH'], namely '/home/jdklassen/projects/env/lib/python3.3/site-packages/tcod/lib/linux64/' (I even tried it without the trailing slash in _get_lib_path_crossplatform(), to no avail), which does contain a libtcod.so file. I guess _bootstrap._gcd_import() is looking somewhere else?

**Comment by HexDecimal** [comment]
You got pretty far into this, I don't think Linux is going to respect the PATH environ.

I have two theoretical ideas: either make a better LD_LIBRARY_PATH attribute before the *.so is built, or force the loading of libtcod.so before importing the _libtcod_X module, the latter is probably going to be the better option since I can't be sure where the module will go on Linux.

Can you put this code in libtcod.py before the imports?

```
import os, ctypes
lib = ctypes.CDLL(os.path.join(__path__[0], 'libtcod.so'))
```

I'll see if I can add the changes you mentioned and get it compiled myself.

**Comment by HexDecimal** [comment]
I finally got it working on my end, the ctypes trick worked.  I probably couldn't have done it without you setting me on the right path though.

I'll put it on pypi soon then close this issue.
