### ISSUE TITLE
Install failing with both setup.py and pip, Python 3.5.2, Linux 64-bit (Ubuntu)

### ISSUE THREAD

**Issue by s-cassidy** [HexDecimal/libtcod-cffi#5]
Sorry I was just being a noob

**Comment by SCassidy-UK** [comment]
Okay, that was just my inability to understand gcc errors. Fixed by obviously installing the correct version of SDL.

Now I am having following problem on import tdl:

import tdl
Traceback (most recent call last):
  File "/home/sam/libtcod/libtcod-cffi-master/tcod/libtcod.py", line 45, in <module>
    import _libtcod # PyPy
ImportError: No module named '_libtcod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/anaconda3/lib/python3.5/site-packages/tdl/__init__.py", line 76, in <module>
    from tcod import ffi as _ffi
  File "/home/sam/libtcod/libtcod-cffi-master/tcod/__init__.py", line 20, in <module>
    from .libtcod import lib, ffi, _lib, _ffi, _unpack_char_p
  File "/home/sam/libtcod/libtcod-cffi-master/tcod/libtcod.py", line 55, in <module>
    _libtcod = _importlib.import_module(_module_name, 'tcod')
  File "/home/sam/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'tcod._libtcod_cp35_x64'
